name: cfm
channels:
  - anaconda
  - conda-forge
  - albumentations
  - defaults
dependencies:
  - fiona
  - gdal
  - imageio
  - keras-gpu=2.2.4
  - matplotlib
  - networkx
  - opencv
  - scikit-image
  - scikit-learn
  - scipy
  - shapely
  - zlib
  - pip:
    - albumentations==0.3.0
    - imgaug==0.2.6
    - numpngw==0.0.8
    - pypng==0.0.20
    - pyproj
    - segmentation-models==0.2.1

