name: rasterio
channels:
  - main
  - conda-forge
  - albumentations
  - defaults
dependencies:
  - descartes=1.1.0
  - fiona=1.8.9.post2
  - gdal=2.4.3
  - matplotlib=3.2.1=0
  - networkx=2.4
  - numpy=1.18.4
  - opencv=4.2.0
  - pandas=1.1.1
  - proj4=6.1.1
  - py-opencv=4.2.0
  - pyproj=2.3.1
  - python=3.6.10
  - rasterio=1.1.2
  - scikit-image=0.17.2
  - scikit-learn=0.23.1
  - scipy=1.3.1
  - shapely=1.6.4
  - tifffile=2020.5.11

