name: cfm
channels:
  - anaconda
  - conda-forge
  - albumentations
  - defaults
dependencies:
  - fiona=1.8.4
  - gdal=2.3.3
  - imageio=2.5.0
  - keras-gpu=2.2.4
  - matplotlib=3.0.3
  - networkx=2.3
  - opencv=3.3.1
  - pandas=0.24.2
  - python=3.6.8
  - scikit-image=0.15.0
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - shapely=1.6.4
  - zlib=1.2.11
  - pip:
    - albumentations==0.3.0
    - imgaug==0.2.6
    - numpngw==0.0.8
    - pypng==0.0.20
    - pyproj==2.4.2.post1
    - segmentation-models==0.2.1

